import Foundation

struct SwiftCodeGenerator: Sendable {
    init() {}

    func generate(
        namespace: String,
        schema: GraphQLSchema,
        documents: GraphQLDocumentDefinitions,
        scalarMappings: [String: String] = [:]
    ) throws -> String {
        var output: [String] = []
        output.append(generateHeader(namespace: namespace, schema: schema, scalarMappings: scalarMappings))
        output.append(generateEnums(schema.enums.values.sorted { $0.name < $1.name }, namespace: namespace))
        output.append(generateInputObjects(schema.inputObjects.values.sorted { $0.name < $1.name }, schema: schema, namespace: namespace, scalarMappings: scalarMappings))
        output.append(try generateFragments(documents.fragments, schema: schema, namespace: namespace, scalarMappings: scalarMappings))
        output.append(try generateOperations(documents.operations, fragments: documents.fragments, schema: schema, namespace: namespace, scalarMappings: scalarMappings))
        return output.joined(separator: "\n")
    }

    private func generateHeader(namespace: String, schema: GraphQLSchema, scalarMappings: [String: String]) -> String {
        var imports = [
            "import Foundation",
            "import SwiftGraphQLClient"
        ]
        if schema.scalars.contains("Upload") {
            imports.append("import SwiftGraphQLUpload")
        }

        var aliases = ["  public typealias ID = String"]
        let builtInScalars: Set<String> = ["String", "Int", "Float", "Boolean", "ID"]
        for scalar in schema.scalars.sorted() where !builtInScalars.contains(scalar) {
            let swiftType = scalarMappings[scalar] ?? (scalar == "Upload" ? "GraphQLUpload" : "String")
            aliases.append("  public typealias \(scalar) = \(swiftType)")
        }

        return """
        // @generated
        // This file was generated by swift-graphql-codegen.

        \(imports.joined(separator: "\n"))

        public enum \(namespace) {
        \(aliases.joined(separator: "\n"))
        }

        """
    }

    private func generateEnums(_ enums: [GraphQLEnumDefinition], namespace: String) -> String {
        guard !enums.isEmpty else { return "" }
        var output = "public extension \(namespace) {\n"
        for enumDefinition in enums {
            output += "  enum \(enumDefinition.name): String, Codable, Sendable, CaseIterable {\n"
            for enumCase in enumDefinition.cases {
                output += "    case \(swiftEnumCaseName(enumCase)) = \"\(enumCase)\"\n"
            }
            output += "  }\n\n"
        }
        output += "}\n"
        return output
    }

    private func generateInputObjects(
        _ inputObjects: [GraphQLInputObjectDefinition],
        schema: GraphQLSchema,
        namespace: String,
        scalarMappings: [String: String]
    ) -> String {
        guard !inputObjects.isEmpty else { return "" }
        var output = "public extension \(namespace) {\n"
        for inputObject in inputObjects {
            output += "  struct \(inputObject.name): Encodable, Sendable, GraphQLVariableMapConvertible {\n"
            for field in inputObject.fields {
                output += "    public var \(escapedIdentifier(field.name)): \(swiftInputType(field.type, schema: schema, scalarMappings: scalarMappings))\n"
            }
            output += "\n"
            output += "    public init(\n"
            output += inputObject.fields.enumerated().map { index, field in
                let defaultValue = field.type.nullable ? " = .none" : ""
                let suffix = index == inputObject.fields.count - 1 ? "" : ","
                return "      \(escapedIdentifier(field.name)): \(swiftInputType(field.type, schema: schema, scalarMappings: scalarMappings))\(defaultValue)\(suffix)"
            }.joined(separator: "\n")
            output += "\n    ) {\n"
            for field in inputObject.fields {
                output += "      self.\(escapedIdentifier(field.name)) = \(escapedIdentifier(field.name))\n"
            }
            output += "    }\n\n"
            output += "    public func graphQLVariableMap() throws -> [String: GraphQLJSONValue] {\n"
            output += "      var builder = GraphQLVariableBuilder()\n"
            for field in inputObject.fields {
                output += "      try builder.set(\"\(field.name)\", \(escapedIdentifier(field.name)))\n"
            }
            output += "      return builder.build()\n"
            output += "    }\n"
            output += "  }\n\n"
        }
        output += "}\n"
        return output
    }

    private func generateFragments(
        _ fragments: [String: GraphQLFragmentDefinition],
        schema: GraphQLSchema,
        namespace: String,
        scalarMappings: [String: String]
    ) throws -> String {
        guard !fragments.isEmpty else { return "" }
        var output = "public extension \(namespace) {\n"
        for fragment in fragments.values.sorted(by: { $0.name < $1.name }) {
            let selectionSet = try GraphQLSelectionParser.parseSelectionSet(in: fragment.source)
            let model = try buildSelectionSet(
                name: fragment.name,
                parentGraphQLType: fragment.typeName,
                selections: selectionSet.selections,
                fragments: fragments,
                schema: schema,
                scalarMappings: scalarMappings
            )
            output += renderSelectionSet(model, indent: 2)
            output += "\n"
        }
        output += "}\n"
        return output
    }

    private func generateOperations(
        _ operations: [GraphQLOperationDefinition],
        fragments: [String: GraphQLFragmentDefinition],
        schema: GraphQLSchema,
        namespace: String,
        scalarMappings: [String: String]
    ) throws -> String {
        guard !operations.isEmpty else { return "" }
        var output = "public extension \(namespace) {\n"
        for operation in operations.sorted(by: { operationStructName($0) < operationStructName($1) }) {
            let structName = operationStructName(operation)
            let selectionSet = try GraphQLSelectionParser.parseSelectionSet(in: operation.source)
            let dataModel = try buildSelectionSet(
                name: "Data",
                parentGraphQLType: rootTypeName(for: operation.kind),
                selections: selectionSet.selections,
                fragments: fragments,
                schema: schema,
                scalarMappings: scalarMappings
            )

            output += "  struct \(structName): \(operationProtocol(operation.kind)) {\n"
            output += "    public static let operationName = \"\(operation.name)\"\n"
            output += "    public static let document = #\"\"\"\n\(documentSource(for: operation, fragments: fragments))\n\"\"\"#\n\n"
            output += "    public static let selections: [SwiftGraphQLClient.GraphQLSelection] = \(renderSelectionMetadata(selectionSet.selections, indent: 4))\n\n"
            for variable in operation.variables {
                output += "    public var \(escapedIdentifier(variable.name)): \(swiftInputType(variable.type, schema: schema, scalarMappings: scalarMappings))\n"
            }
            if !operation.variables.isEmpty {
                output += "\n"
                output += "    public init(\n"
                output += operation.variables.enumerated().map { index, variable in
                    let defaultValue = swiftDefaultValue(for: variable, schema: schema)
                    let suffix = index == operation.variables.count - 1 ? "" : ","
                    return "      \(escapedIdentifier(variable.name)): \(swiftInputType(variable.type, schema: schema, scalarMappings: scalarMappings))\(defaultValue)\(suffix)"
                }.joined(separator: "\n")
                output += "\n    ) {\n"
                for variable in operation.variables {
                    output += "      self.\(escapedIdentifier(variable.name)) = \(escapedIdentifier(variable.name))\n"
                }
                output += "    }\n\n"
                output += "    public struct Variables: Encodable, Sendable, GraphQLVariableMapConvertible {\n"
                for variable in operation.variables {
                    output += "      public var \(escapedIdentifier(variable.name)): \(swiftInputType(variable.type, schema: schema, scalarMappings: scalarMappings))\n"
                }
                output += "\n"
                output += "      public func graphQLVariableMap() throws -> [String: GraphQLJSONValue] {\n"
                output += "        var builder = GraphQLVariableBuilder()\n"
                for variable in operation.variables {
                    output += "        try builder.set(\"\(variable.name)\", \(escapedIdentifier(variable.name)))\n"
                }
                output += "        return builder.build()\n"
                output += "      }\n"
                output += "    }\n\n"
                output += "    public var variables: Variables {\n"
                output += "      Variables(\n"
                output += operation.variables.enumerated().map { index, variable in
                    let suffix = index == operation.variables.count - 1 ? "" : ","
                    return "        \(escapedIdentifier(variable.name)): \(escapedIdentifier(variable.name))\(suffix)"
                }.joined(separator: "\n")
                output += "\n      )\n"
                output += "    }\n\n"
            } else {
                output += "    public init() {}\n\n"
            }
            output += renderSelectionSet(dataModel, indent: 4)
            output += "  }\n\n"
        }
        output += "}\n"
        return output
    }

    private func renderSelectionSet(_ model: GeneratedSelectionSet, indent: Int) -> String {
        let baseIndent = String(repeating: " ", count: indent)
        let innerIndent = String(repeating: " ", count: indent + 2)
        let access = indent == 2 ? "" : "public "
        var output = "\(baseIndent)\(access)struct \(model.name): Codable, Sendable, Equatable {\n"
        for field in model.fields {
            output += "\(innerIndent)public var \(field.propertyName): \(field.swiftType)\n"
        }

        if !model.fields.isEmpty {
            output += "\n"
        }
        if !model.fragmentSpreads.isEmpty {
            output += "\(innerIndent)public var fragments: Fragments { Fragments(base: self) }\n\n"
        }

        output += renderInitializer(for: model, indent: indent + 2)
        if needsCodingKeys(model.fields) {
            output += "\n"
            output += renderCodingKeys(for: model.fields, indent: indent + 2)
        }
        if !model.fragmentSpreads.isEmpty {
            output += "\n"
            output += renderFragmentContainer(for: model, indent: indent + 2)
        }
        for nested in model.nestedSelectionSets {
            output += "\n"
            output += renderSelectionSet(nested, indent: indent + 2)
        }
        output += "\(baseIndent)}\n"
        return output
    }

    private func renderInitializer(for model: GeneratedSelectionSet, indent: Int) -> String {
        let baseIndent = String(repeating: " ", count: indent)
        let bodyIndent = String(repeating: " ", count: indent + 2)
        guard !model.fields.isEmpty else {
            return "\(baseIndent)public init() {}\n"
        }

        var output = "\(baseIndent)public init(\n"
        output += model.fields.enumerated().map { index, field in
            let defaultValue = field.swiftType.hasSuffix("?") ? " = nil" : ""
            let suffix = index == model.fields.count - 1 ? "" : ","
            return "\(bodyIndent)\(field.propertyName): \(field.swiftType)\(defaultValue)\(suffix)"
        }.joined(separator: "\n")
        output += "\n\(baseIndent)) {\n"
        for field in model.fields {
            output += "\(bodyIndent)self.\(field.propertyName) = \(field.propertyName)\n"
        }
        output += "\(baseIndent)}\n"
        return output
    }

    private func renderCodingKeys(for fields: [GeneratedField], indent: Int) -> String {
        let baseIndent = String(repeating: " ", count: indent)
        let caseIndent = String(repeating: " ", count: indent + 2)
        var output = "\(baseIndent)private enum CodingKeys: String, CodingKey {\n"
        for field in fields {
            if field.propertyName == field.responseName {
                output += "\(caseIndent)case \(field.propertyName)\n"
            } else {
                output += "\(caseIndent)case \(field.propertyName) = \"\(field.responseName)\"\n"
            }
        }
        output += "\(baseIndent)}\n"
        return output
    }

    private func renderFragmentContainer(for model: GeneratedSelectionSet, indent: Int) -> String {
        let baseIndent = String(repeating: " ", count: indent)
        let innerIndent = String(repeating: " ", count: indent + 2)
        var output = "\(baseIndent)public struct Fragments: Sendable {\n"
        output += "\(innerIndent)private let base: \(model.name)\n\n"
        output += "\(innerIndent)fileprivate init(base: \(model.name)) {\n"
        output += "\(innerIndent)  self.base = base\n"
        output += "\(innerIndent)}\n\n"
        for fragmentName in model.fragmentSpreads {
            output += "\(innerIndent)public var \(swiftPropertyName(fragmentName)): \(fragmentName) {\n"
            output += "\(innerIndent)  GraphQLFragmentProjection.project(base, to: \(fragmentName).self)\n"
            output += "\(innerIndent)}\n"
        }
        output += "\(baseIndent)}\n"
        return output
    }

    private func needsCodingKeys(_ fields: [GeneratedField]) -> Bool {
        fields.contains { $0.propertyName != $0.responseName || $0.propertyName.hasPrefix("`") }
    }

    private func buildSelectionSet(
        name: String,
        parentGraphQLType: String,
        selections: [GraphQLSelection],
        fragments: [String: GraphQLFragmentDefinition],
        schema: GraphQLSchema,
        scalarMappings: [String: String]
    ) throws -> GeneratedSelectionSet {
        let expanded = try expandSelections(
            selections,
            parentGraphQLType: parentGraphQLType,
            fragments: fragments,
            schema: schema,
            visitedFragments: []
        )
        var generatedFields: [GeneratedField] = []
        var nestedSelectionSets: [GeneratedSelectionSet] = []

        for field in expanded.fields {
            let graphQLType = schema.objects[parentGraphQLType]?.fields[field.name]?.type
            let effectiveType = graphQLType ?? (field.name == "__typename" ? .nonNull(.named("String")) : .named("AWSJSON"))
            let fieldParentType = effectiveType.namedType
            let nestedName = swiftSelectionSetName(for: field.responseName, type: effectiveType)
            let hasNestedObject = !field.selections.isEmpty && schema.objects[fieldParentType] != nil
            if hasNestedObject {
                nestedSelectionSets.append(try buildSelectionSet(
                    name: nestedName,
                    parentGraphQLType: fieldParentType,
                    selections: field.selections,
                    fragments: fragments,
                    schema: schema,
                    scalarMappings: scalarMappings
                ))
            }
            generatedFields.append(GeneratedField(
                responseName: field.responseName,
                propertyName: escapedIdentifier(swiftPropertyName(field.responseName)),
                swiftType: swiftOutputType(
                    effectiveType,
                    nestedTypeName: hasNestedObject ? nestedName : nil,
                    schema: schema,
                    scalarMappings: scalarMappings
                )
            ))
        }

        return GeneratedSelectionSet(
            name: name,
            fields: generatedFields,
            fragmentSpreads: expanded.fragmentSpreads.map(swiftTypeName).sorted(),
            nestedSelectionSets: nestedSelectionSets
        )
    }

    private func expandSelections(
        _ selections: [GraphQLSelection],
        parentGraphQLType: String,
        fragments: [String: GraphQLFragmentDefinition],
        schema: GraphQLSchema,
        visitedFragments: Set<String>
    ) throws -> ExpandedSelections {
        var fields: [MergedField] = []
        var fieldIndexes: [String: Int] = [:]
        var fragmentSpreads: [String] = []

        func merge(_ field: MergedField) {
            if let existingIndex = fieldIndexes[field.responseName] {
                fields[existingIndex].selections.append(contentsOf: field.selections)
            } else {
                fieldIndexes[field.responseName] = fields.count
                fields.append(field)
            }
        }

        for selection in selections {
            switch selection {
            case .field(let field):
                merge(MergedField(name: field.name, responseName: field.responseName, selections: field.selections))
            case .fragmentSpread(let name):
                guard let fragment = fragments[name], !visitedFragments.contains(name) else { continue }
                fragmentSpreads.append(name)
                let selectionSet = try GraphQLSelectionParser.parseSelectionSet(in: fragment.source)
                var visited = visitedFragments
                visited.insert(name)
                let expanded = try expandSelections(
                    selectionSet.selections,
                    parentGraphQLType: fragment.typeName,
                    fragments: fragments,
                    schema: schema,
                    visitedFragments: visited
                )
                for field in expanded.fields {
                    merge(field)
                }
            case .inlineFragment(let typeName, let nestedSelections):
                let expanded = try expandSelections(
                    nestedSelections,
                    parentGraphQLType: typeName ?? parentGraphQLType,
                    fragments: fragments,
                    schema: schema,
                    visitedFragments: visitedFragments
                )
                for field in expanded.fields {
                    merge(field)
                }
            }
        }

        return ExpandedSelections(
            fields: fields,
            fragmentSpreads: Array(Set(fragmentSpreads)).sorted()
        )
    }

    private func swiftOutputType(
        _ type: GraphQLTypeReference,
        nestedTypeName: String?,
        schema: GraphQLSchema,
        scalarMappings: [String: String]
    ) -> String {
        if case .nonNull(let inner) = type {
            return swiftNonNullableOutputType(inner, nestedTypeName: nestedTypeName, schema: schema, scalarMappings: scalarMappings)
        }
        return swiftNonNullableOutputType(type, nestedTypeName: nestedTypeName, schema: schema, scalarMappings: scalarMappings) + "?"
    }

    private func swiftNonNullableOutputType(
        _ type: GraphQLTypeReference,
        nestedTypeName: String?,
        schema: GraphQLSchema,
        scalarMappings: [String: String]
    ) -> String {
        switch type {
        case .named(let name):
            if schema.objects[name] != nil, let nestedTypeName {
                return nestedTypeName
            }
            if schema.enums[name] != nil {
                return name
            }
            switch name {
            case "ID", "String":
                return name
            case "Int":
                return "Int"
            case "Float":
                return "Double"
            case "Boolean":
                return "Bool"
            default:
                return scalarMappings[name] ?? (schema.scalars.contains(name) ? name : "GraphQLJSONValue")
            }
        case .list(let inner):
            return "[\(swiftListElementOutputType(inner, nestedTypeName: nestedTypeName, schema: schema, scalarMappings: scalarMappings))]"
        case .nonNull(let inner):
            return swiftNonNullableOutputType(inner, nestedTypeName: nestedTypeName, schema: schema, scalarMappings: scalarMappings)
        }
    }

    private func swiftListElementOutputType(
        _ type: GraphQLTypeReference,
        nestedTypeName: String?,
        schema: GraphQLSchema,
        scalarMappings: [String: String]
    ) -> String {
        if case .nonNull(let inner) = type {
            return swiftNonNullableOutputType(inner, nestedTypeName: nestedTypeName, schema: schema, scalarMappings: scalarMappings)
        }
        return swiftNonNullableOutputType(type, nestedTypeName: nestedTypeName, schema: schema, scalarMappings: scalarMappings) + "?"
    }

    private func documentSource(
        for operation: GraphQLOperationDefinition,
        fragments: [String: GraphQLFragmentDefinition]
    ) -> String {
        var emitted = Set<String>()
        var sources = [operation.source]
        func appendFragments(_ names: Set<String>) {
            for name in names.sorted() where !emitted.contains(name) {
                guard let fragment = fragments[name] else { continue }
                emitted.insert(name)
                sources.append(fragment.source)
                appendFragments(fragment.fragmentSpreads)
            }
        }
        appendFragments(operation.fragmentSpreads)
        return sources.joined(separator: "\n\n")
    }

    private func rootTypeName(for kind: GraphQLOperationDefinition.Kind) -> String {
        switch kind {
        case .query: return "Query"
        case .mutation: return "Mutation"
        case .subscription: return "Subscription"
        }
    }

    private func operationStructName(_ operation: GraphQLOperationDefinition) -> String {
        operation.name + operation.kind.rawValue.capitalized
    }

    private func operationProtocol(_ kind: GraphQLOperationDefinition.Kind) -> String {
        switch kind {
        case .query: return "GraphQLQuery"
        case .mutation: return "GraphQLMutation"
        case .subscription: return "GraphQLSubscription"
        }
    }

    private func swiftInputType(
        _ type: GraphQLTypeReference,
        schema: GraphQLSchema,
        scalarMappings: [String: String]
    ) -> String {
        if type.nullable {
            return "GraphQLNullable<\(swiftNonNullableInputType(type.unwrapped, schema: schema, scalarMappings: scalarMappings))>"
        }
        return swiftNonNullableInputType(type.unwrapped, schema: schema, scalarMappings: scalarMappings)
    }

    private func swiftNonNullableInputType(
        _ type: GraphQLTypeReference,
        schema: GraphQLSchema,
        scalarMappings: [String: String]
    ) -> String {
        switch type {
        case .named(let name):
            if schema.enums[name] != nil {
                return "GraphQLEnum<\(name)>"
            }
            switch name {
            case "ID", "String", "AWSDateTime", "AWSJSON":
                return name
            case "Int":
                return "Int32"
            case "Float":
                return "Double"
            case "Boolean":
                return "Bool"
            default:
                return scalarMappings[name] ?? name
            }
        case .list(let inner):
            return "[\(swiftNonNullableInputType(inner.unwrapped, schema: schema, scalarMappings: scalarMappings))]"
        case .nonNull(let inner):
            return swiftNonNullableInputType(inner, schema: schema, scalarMappings: scalarMappings)
        }
    }

    private func swiftDefaultValue(for variable: GraphQLVariableDefinition, schema: GraphQLSchema) -> String {
        if let defaultValue = variable.defaultValue {
            return " = \(swiftLiteral(defaultValue, type: variable.type, schema: schema))"
        }
        return variable.type.nullable ? " = .none" : ""
    }

    private func swiftLiteral(_ rawValue: String, type: GraphQLTypeReference, schema: GraphQLSchema) -> String {
        let trimmed = rawValue.trimmingCharacters(in: .whitespaces)
        let namedType = type.namedType
        if schema.enums[namedType] != nil {
            return "GraphQLEnum(\(namespaceCase(trimmed)))"
        }
        switch namedType {
        case "String", "ID", "AWSDateTime", "AWSJSON":
            return trimmed.hasPrefix("\"") ? trimmed : "\"\(trimmed)\""
        case "Float":
            return trimmed
        case "Int":
            return trimmed
        case "Boolean":
            return trimmed.lowercased()
        default:
            return trimmed
        }
    }

    private func renderSelectionMetadata(_ selections: [GraphQLSelection], indent: Int) -> String {
        guard !selections.isEmpty else { return "[]" }
        let baseIndent = String(repeating: " ", count: indent)
        let itemIndent = String(repeating: " ", count: indent + 2)
        var output = "[\n"
        for (index, selection) in selections.enumerated() {
            output += itemIndent
            output += renderSelectionMetadataItem(selection, indent: indent + 2)
            if index != selections.count - 1 {
                output += ","
            }
            output += "\n"
        }
        output += "\(baseIndent)]"
        return output
    }

    private func renderSelectionMetadataItem(_ selection: GraphQLSelection, indent: Int) -> String {
        switch selection {
        case .field(let field):
            return ".field(name: \(swiftStringLiteral(field.name)), responseName: \(swiftStringLiteral(field.responseName)), selections: \(renderSelectionMetadata(field.selections, indent: indent)))"
        case .fragmentSpread(let name):
            return ".fragmentSpread(\(swiftStringLiteral(name)))"
        case .inlineFragment(let typeName, let selections):
            let renderedTypeName = typeName.map(swiftStringLiteral) ?? "nil"
            return ".inlineFragment(typeName: \(renderedTypeName), selections: \(renderSelectionMetadata(selections, indent: indent)))"
        }
    }

    private func swiftStringLiteral(_ value: String) -> String {
        let escaped = value
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
            .replacingOccurrences(of: "\n", with: "\\n")
            .replacingOccurrences(of: "\r", with: "\\r")
            .replacingOccurrences(of: "\t", with: "\\t")
        return "\"\(escaped)\""
    }

    private func swiftSelectionSetName(for responseName: String, type: GraphQLTypeReference) -> String {
        let name = type.isList ? singularized(responseName) : responseName
        return swiftTypeName(name)
    }

    private func swiftTypeName(_ rawName: String) -> String {
        let property = swiftPropertyName(rawName).trimmingCharacters(in: CharacterSet(charactersIn: "`"))
        return property.split(separator: "_").map { part in
            part.prefix(1).uppercased() + part.dropFirst()
        }.joined()
    }

    private func swiftPropertyName(_ rawName: String) -> String {
        let pieces = rawName.split(separator: "_")
        guard let first = pieces.first else { return rawName }
        let joined = ([String(first)] + pieces.dropFirst().map { $0.prefix(1).uppercased() + $0.dropFirst() }).joined()
        guard let firstCharacter = joined.first else { return joined }
        return firstCharacter.lowercased() + joined.dropFirst()
    }

    private func escapedIdentifier(_ name: String) -> String {
        let reserved: Set<String> = [
            "associatedtype", "break", "case", "catch", "class", "continue", "default", "defer",
            "deinit", "do", "else", "enum", "extension", "fallthrough", "false", "fileprivate",
            "for", "func", "guard", "if", "import", "in", "init", "inout", "internal", "is",
            "let", "nil", "open", "operator", "private", "protocol", "public", "repeat", "rethrows",
            "return", "self", "Self", "static", "struct", "subscript", "super", "switch", "throw",
            "throws", "true", "try", "typealias", "var", "where", "while"
        ]
        return reserved.contains(name) ? "`\(name)`" : name
    }

    private func singularized(_ rawName: String) -> String {
        if rawName.hasSuffix("ies"), rawName.count > 3 {
            return String(rawName.dropLast(3)) + "y"
        }
        if rawName.hasSuffix("s"), rawName.count > 1 {
            return String(rawName.dropLast())
        }
        return rawName
    }

    private func namespaceCase(_ rawValue: String) -> String {
        ".\(swiftEnumCaseName(rawValue.trimmingCharacters(in: CharacterSet(charactersIn: "\"'"))))"
    }

    private func swiftEnumCaseName(_ rawName: String) -> String {
        let pieces = rawName.lowercased().split(separator: "_")
        guard let first = pieces.first else { return rawName.lowercased() }
        return ([String(first)] + pieces.dropFirst().map { $0.prefix(1).uppercased() + $0.dropFirst() }).joined()
    }
}

private struct GeneratedSelectionSet {
    var name: String
    var fields: [GeneratedField]
    var fragmentSpreads: [String]
    var nestedSelectionSets: [GeneratedSelectionSet]
}

private struct GeneratedField {
    var responseName: String
    var propertyName: String
    var swiftType: String
}

private struct MergedField {
    var name: String
    var responseName: String
    var selections: [GraphQLSelection]
}

private struct ExpandedSelections {
    var fields: [MergedField]
    var fragmentSpreads: [String]
}

private extension GraphQLTypeReference {
    var isList: Bool {
        switch self {
        case .list:
            return true
        case .nonNull(let inner):
            return inner.isList
        case .named:
            return false
        }
    }
}
